//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to AAHS
    ///AALS
    ///ABAS
    ///ABBA
    ///ABBE
    ///ABED
    ///ABET
    ///ABLE
    ///ABLY
    ///ABRI
    ///ABUT
    ///ABYE
    ///ABYS
    ///ACAI
    ///ACED
    ///ACES
    ///ACHE
    ///ACHY
    ///ACID
    ///ACME
    ///ACNE
    ///ACRE
    ///ACRO
    ///ACTA
    ///ACTS
    ///ACYL
    ///ADDS
    ///ADIT
    ///ADOS
    ///ADZE
    ///AEON
    ///AERO
    ///AERY
    ///AFAR
    ///AFRO
    ///AGAR
    ///AGAS
    ///AGED
    ///AGEE
    ///AGER
    ///AGES
    ///AGHA
    ///AGIN
    ///AGIO
    ///AGLU
    ///AGLY
    ///AGMA
    ///AGOG
    ///AGON
    ///AGRO
    ///AGUE
    ///AHED
    ///AHEM
    ///AHIS
    ///AHOY
    ///AIDE
    ///AIDS
    ///AILS
    ///AIMS
    ///AINS
    ///AIRN
    ///AIRS
    ///AIRT
    ///AIRY
    ///AITS
    ///AJAR
    ///AJEE
    ///AJIS
    ///AKEE
    ///AKIN
    ///ALAE
    ///ALAN
    ///ALAR
    ///ALAS
    ///ALBA
    ///ALBS
    ///ALEC
    ///ALEE
    ///ALEF
    ///ALES
    ///ALFA
    ///ALGA
    ///ALIF
    ///ALIT
    ///ALKY
    ///ALLS
    ///ALLY
    ///ALMA
    ///ALME
    ///ALMS
    ///ALOE
    ///ALOW
    ///ALPS
    ///ALSO
    ///ALTO
    ///ALTS
    ///ALUM
    ///AMAH
    ///AMAS
    ///AMBO
    ///AMEN
    ///AMIA
    ///AM [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string dictionary {
        get {
            return ResourceManager.GetString("dictionary", resourceCulture);
        }
    }
}
